use_frameworks!

target 'Miscel_Example' do
  
  pod 'Layitout', :git => 'https://github.com/buscarini/layitout.git', :branch => 'master'
  pod 'Miscel', :path => '../'

  target 'Miscel_Tests' do
    inherit! :search_paths

    
  end
end
